<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/state';
	import {
		FileText,
		CheckCircle2,
		ChevronRight,
		Loader2,
		AlertCircle,
		Brain,
		ClipboardList,
		XCircle,
		Mail
	} from 'lucide-svelte';
	import { format } from 'date-fns';
	import { locale } from '$lib/i18n';
	import StatusBadge from '$lib/components/StatusBadge.svelte';
	import { type DocumentSummary } from '$lib/api/types';

	const id = page.params.id;
	let doc = $state<DocumentSummary | null>(null);
	let isLoading = $state(true);
	let errorMsg = $state('');

	let feedbackText = $state('');
	let decision = $state('APPROVED'); // 'APPROVED' or 'REJECTED'
	let submitting = $state(false);
	let submitted = $state(false);
	let generatingLeaderBrief = $state(false);
	let selectedFileIndex = $state(0);

	const ui = $derived(
		$locale === 'en'
			? {
					title: 'Record Approval',
					back: 'Back',
					badge: 'Leadership Approval',
					originalRecord: 'Original Record',
					file: 'File',
					openFullscreen: 'Open fullscreen',
					officerBrief: 'Officer Brief (AI)',
					officerBriefFallback:
						'(Document summary shown while the officer brief is still being generated by AI)',
					noOfficerBrief: 'No consolidated brief is available yet.',
					reviewMinutes: 'Professional Review Minutes',
					officerRole: 'Officer',
					recommendApprove: 'Recommend Approval',
					requestRevision: 'Request Revision',
					emptyMinutes: '(No review minutes content)',
					aiSummaryTitle: 'Inter-agency Memo (AI Summary)',
					leaderDecision: 'Leadership Decision',
					leaderDecisionHint:
						'The result will be sent to the citizen by email immediately after leadership finalizes the decision.',
					approve: 'Approve',
					approveHint: 'Accept the recommendation',
					revise: 'Request changes',
					reviseHint: 'Request additional content',
					reject: 'Reject',
					rejectHint: 'Does not meet requirements',
					directiveRequired: 'Directive note (required)',
					directiveOptional: 'Directive note (optional)',
					drafting: 'Drafting...',
					aiDraft: 'AI Draft',
					approvePlaceholder: 'Approve according to the officer recommendation...',
					aiDraftPlaceholder: 'Press "AI Draft" to fill in the directive automatically...',
					processing: 'Processing...',
					approveNotify: 'Approve & Notify Citizen',
					rejectNotify: 'Reject & Send Email Notification',
					revisionNotify: 'Request Record Revision',
					approveMailHint:
						'The system will automatically send the approval confirmation email to the citizen.',
					rejectMailHint:
						'The system will automatically send the rejection email with the reason to the citizen.',
					revisionHint: 'The record will be returned to the officer for revision.',
					approvedResult: 'The record has been approved',
					approvedMailSent: 'Confirmation email has been sent to the citizen.',
					rejectedResult: 'The record has been rejected',
					rejectedMailSent: 'Notification email has been sent to the citizen.',
					revisionResult: 'The record requires revision',
					revisionStatusHint: 'The record status has been moved back to the officer.',
					backMissionControl: 'Back to Mission Control',
					notReady: 'The record has not been submitted by the officer yet.'
				}
			: {
					title: 'Phê duyệt hồ sơ',
					back: 'Quay lại',
					badge: 'Phê duyệt cấp Lãnh đạo',
					originalRecord: 'Hồ sơ gốc',
					file: 'Tệp',
					openFullscreen: 'Mở toàn màn hình',
					officerBrief: 'Tóm tắt báo cáo Chuyên viên (AI)',
					officerBriefFallback: '(Tóm tắt tài liệu — báo cáo Chuyên viên đang được AI xử lý)',
					noOfficerBrief: 'Chưa có báo cáo tổng hợp.',
					reviewMinutes: 'Biên bản xử lý chuyên môn',
					officerRole: 'Chuyên viên',
					recommendApprove: 'Đề nghị Phê duyệt',
					requestRevision: 'Yêu cầu Sửa đổi',
					emptyMinutes: '(Không có nội dung biên bản)',
					aiSummaryTitle: 'Tờ trình Liên ngành (AI Tổng hợp)',
					leaderDecision: 'Quyết định của Lãnh đạo',
					leaderDecisionHint:
						'Kết quả sẽ được thông báo đến công dân qua email ngay sau khi Lãnh đạo chốt quyết định.',
					approve: 'Phê duyệt',
					approveHint: 'Đồng ý đề xuất',
					revise: 'Sửa đổi',
					reviseHint: 'Yêu cầu bổ sung nội dung',
					reject: 'Từ chối',
					rejectHint: 'Không đạt yêu cầu',
					directiveRequired: 'Ý kiến chỉ đạo (bắt buộc)',
					directiveOptional: 'Ý kiến chỉ đạo (tùy chọn)',
					drafting: 'Đang soạn...',
					aiDraft: 'AI Soạn thảo',
					approvePlaceholder: 'Đồng ý phê duyệt theo đề xuất của Chuyên viên...',
					aiDraftPlaceholder: 'Nhấn "AI Soạn thảo" để tự động điền ý kiến...',
					processing: 'Đang xử lý...',
					approveNotify: 'Phê duyệt & Thông báo Công dân',
					rejectNotify: 'Từ chối & Gửi email Thông báo',
					revisionNotify: 'Yêu cầu sửa đổi hồ sơ',
					approveMailHint: 'Hệ thống sẽ tự động gửi email xác nhận phê duyệt đến công dân.',
					rejectMailHint: 'Hệ thống sẽ tự động gửi email thông báo từ chối kèm lý do đến công dân.',
					revisionHint: 'Hồ sơ sẽ được chuyển lại cho Chuyên viên để tiến hành sửa đổi.',
					approvedResult: 'Hồ sơ đã được Phê duyệt',
					approvedMailSent: 'Email xác nhận đã gửi đến công dân.',
					rejectedResult: 'Hồ sơ đã bị Từ chối',
					rejectedMailSent: 'Email thông báo đã gửi đến công dân.',
					revisionResult: 'Hồ sơ được yêu cầu Sửa đổi',
					revisionStatusHint: 'Trạng thái hồ sơ đã được chuyển lại cho Chuyên viên.',
					backMissionControl: 'Quay về Mission Control',
					notReady: 'Hồ sơ chưa được Chuyên viên trình duyệt.'
				}
	);

	async function generateAILeaderBrief() {
		if (!doc) return;
		generatingLeaderBrief = true;
		try {
			const res = await fetch(`/api/documents/${id}/ai-leader-brief`, {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({ decision })
			});
			if (!res.ok) throw new Error(((await res.json()) as any).message || 'Lỗi khi gọi AI');
			const result = (await res.json()) as { report: string };
			feedbackText = result.report;
		} catch (e) {
			alert((e as Error).message);
		} finally {
			generatingLeaderBrief = false;
		}
	}

	onMount(async () => {
		try {
			const res = await fetch(`/api/documents/${id}`);
			if (!res.ok) throw new Error(((await res.json()) as any).message || 'Không thể tải hồ sơ');
			doc = await res.json();
		} catch (e) {
			errorMsg = (e as Error).message;
		} finally {
			isLoading = false;
		}
	});

	async function submitApproval() {
		if (!doc) return;
		submitting = true;
		try {
			const res = await fetch(`/api/documents/${id}/approve`, {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({ decision, feedback: feedbackText })
			});
			if (!res.ok) throw new Error(((await res.json()) as any).message || 'Lỗi khi gửi tác vụ');
			doc.status = decision as any;
			submitted = true;
		} catch (e) {
			alert((e as Error).message);
		} finally {
			submitting = false;
		}
	}

	// Helpers
	const officerBrief = $derived(
		(doc?.extractedData as any)?.ai_officer_brief as string | undefined
	);
	const aiSummary = $derived((doc?.extractedData as any)?.ai_summary as string | undefined);
	const latestOfficerFeedback = $derived(() => {
		const feedbacks: any[] = (doc?.extractedData as any)?.officerFeedback || [];
		return feedbacks.length > 0 ? feedbacks[feedbacks.length - 1] : null;
	});
	const canDecide = $derived(doc?.status === 'PENDING_APPROVAL' && !submitted);
</script>

<svelte:head>
	<title>{ui.title} — DVC Portal</title>
</svelte:head>

<div
	class="flex h-full animate-in flex-col overflow-hidden bg-muted/10 duration-500 fade-in md:flex-row"
>
	<!-- Left Panel: Document viewer -->
	<div
		class="flex w-full flex-col overflow-hidden border-r border-border/40 bg-background md:w-1/2"
	>
		<!-- Header -->
		<div class="border-b border-border/30 bg-muted/10 p-6">
			<div class="mb-4 flex items-center gap-2">
				<a
					href="/portal"
					class="flex items-center gap-1 text-xs font-bold text-muted-foreground transition-colors hover:text-primary"
				>
					<ChevronRight size={14} class="rotate-180" />
					{ui.back}
				</a>
				<span class="text-border/50">•</span>
				<span class="text-[10px] font-black tracking-widest text-primary uppercase">{ui.badge}</span
				>
			</div>

			{#if isLoading}
				<div class="space-y-3">
					<div class="h-4 w-32 animate-pulse rounded bg-muted/40"></div>
					<div class="h-8 w-64 animate-pulse rounded bg-muted/40"></div>
				</div>
			{:else if doc}
				<div class="space-y-1">
					<p class="font-mono text-xs font-bold tracking-[0.2em] text-primary uppercase">
						{doc.trackingCode}
					</p>
					<h2 class="flex items-center gap-3 text-xl font-extrabold text-foreground">
						{ui.originalRecord}
						<StatusBadge status={doc.status} />
					</h2>
				</div>
			{:else if errorMsg}
				<p class="font-bold text-destructive">{errorMsg}</p>
			{/if}
		</div>

		<!-- File viewer -->
		<div class="flex flex-1 flex-col gap-4 overflow-y-auto p-6">
			{#if doc?.rawFileUrls && doc.rawFileUrls.length > 0}
				{#if doc.rawFileUrls.length > 1}
					<div class="flex w-fit gap-1 rounded-xl bg-muted/30 p-1.5">
						{#each doc.rawFileUrls as url, idx}
							<button
								class="rounded-lg px-4 py-2 text-xs font-bold transition-all {selectedFileIndex ===
								idx
									? 'bg-background text-primary shadow-md ring-1 ring-primary/20'
									: 'text-muted-foreground hover:bg-muted/40 hover:text-foreground'}"
								onclick={() => (selectedFileIndex = idx)}
							>
								{ui.file}
								{idx + 1}
							</button>
						{/each}
					</div>
				{/if}

				{@const currentUrl = doc.rawFileUrls[selectedFileIndex] || doc.rawFileUrls[0]}
				<div
					class="flex h-full min-h-[400px] flex-col overflow-hidden rounded-2xl border border-border/50 bg-muted/5"
				>
					<div
						class="flex items-center justify-between border-b border-border/50 bg-background/50 p-3"
					>
						<span class="flex items-center gap-2 text-xs font-bold text-foreground">
							<FileText size={16} class="text-blue-500" />
							{currentUrl.split('/').pop()}
						</span>
						<a
							href={currentUrl}
							target="_blank"
							class="rounded-lg bg-blue-500/10 px-3 py-1 text-xs font-bold text-blue-500 hover:text-blue-600"
							>{ui.openFullscreen}</a
						>
					</div>
					<iframe
						src={currentUrl}
						class="min-h-[600px] w-full flex-1 border-0"
						title="Document Viewer"
					></iframe>
				</div>
			{/if}
		</div>
	</div>

	<!-- Right Panel: Decision -->
	<div
		class="relative z-10 flex w-full flex-col overflow-y-auto bg-background shadow-[-10px_0_30px_rgba(0,0,0,0.02)] md:w-1/2"
	>
		{#if doc}
			<div class="mx-auto w-full max-w-2xl space-y-8 p-8">
				<!-- ── Officer Brief (AI) ── -->
				<div class="space-y-3">
					<div class="flex items-center gap-2">
						<div class="rounded bg-primary/10 p-1.5 text-primary">
							<Brain size={16} />
						</div>
						<h3 class="text-xs font-black tracking-widest text-foreground uppercase">
							{ui.officerBrief}
						</h3>
					</div>

					<div
						class="relative overflow-hidden rounded-2xl border border-primary/20 bg-primary/5 p-5 text-sm leading-relaxed font-medium text-foreground"
					>
						{#if officerBrief}
							{officerBrief}
						{:else if aiSummary}
							<!-- Fallback to document AI summary if officer brief not yet ready -->
							<p class="mb-2 font-sans text-xs text-muted-foreground italic">
								{ui.officerBriefFallback}
							</p>
							{aiSummary}
						{:else}
							<p class="text-xs text-muted-foreground/60 italic">{ui.noOfficerBrief}</p>
						{/if}
						<!-- Shimmer if awaiting -->
						{#if !officerBrief && doc.status === 'PENDING_APPROVAL'}
							<div
								class="absolute inset-x-0 bottom-0 h-px animate-pulse bg-linear-to-r from-transparent via-primary/40 to-transparent"
							></div>
						{/if}
					</div>
				</div>

				<!-- ── Chuyên viên's Biên bản ── -->
				{#if latestOfficerFeedback()}
					{@const fb = latestOfficerFeedback()}
					<div class="space-y-3">
						<div class="flex items-center gap-2">
							<div class="rounded bg-amber-500/10 p-1.5 text-amber-500">
								<ClipboardList size={16} />
							</div>
							<h3 class="text-xs font-black tracking-widest text-foreground uppercase">
								{ui.reviewMinutes}
							</h3>
						</div>

						<div class="space-y-3 rounded-2xl border border-amber-500/20 bg-amber-500/5 p-5">
							<div class="flex items-center justify-between gap-4">
								<div class="flex items-center gap-2">
									<span class="text-xs font-bold text-foreground">{fb.officer}</span>
									<span
										class="rounded bg-muted/40 px-1.5 py-0.5 text-[10px] font-bold tracking-wider text-muted-foreground uppercase"
										>{ui.officerRole}</span
									>
								</div>
								<div class="flex items-center gap-2">
									{#if fb.decision === 'APPROVE'}
										<span
											class="flex items-center gap-1 rounded-full border border-emerald-500/20 bg-emerald-500/10 px-2 py-0.5 text-[10px] font-bold text-emerald-600"
										>
											<CheckCircle2 size={10} />
											{ui.recommendApprove}
										</span>
									{:else}
										<span
											class="flex items-center gap-1 rounded-full border border-amber-500/20 bg-amber-500/10 px-2 py-0.5 text-[10px] font-bold text-amber-600"
										>
											<AlertCircle size={10} />
											{ui.requestRevision}
										</span>
									{/if}
									<span class="text-[10px] text-muted-foreground">
										{format(new Date(fb.timestamp * 1000), 'HH:mm dd/MM/yyyy')}
									</span>
								</div>
							</div>
							<p
								class="border-t border-amber-500/10 pt-3 font-mono text-sm leading-relaxed whitespace-pre-wrap text-foreground"
							>
								{fb.feedback || ui.emptyMinutes}
							</p>
						</div>
					</div>
				{/if}

				<!-- ── Tờ trình Liên ngành (from ai-summary) ── -->
				{#if aiSummary}
					<div class="space-y-3">
						<h3 class="text-xs font-black tracking-widest text-muted-foreground uppercase">
							{ui.aiSummaryTitle}
						</h3>
						<div
							class="rounded-2xl border border-border/30 bg-muted/10 p-5 font-sans text-sm leading-relaxed text-foreground"
						>
							{aiSummary}
						</div>
					</div>
				{/if}

				<div class="h-px w-full bg-border/40"></div>

				<!-- ── Decision Form ── -->
				<div class="space-y-6">
					<div class="space-y-1">
						<h3 class="text-sm font-extrabold tracking-tight text-foreground uppercase">
							{ui.leaderDecision}
						</h3>
						<p class="text-xs leading-relaxed text-muted-foreground">
							{ui.leaderDecisionHint}
						</p>
					</div>

					{#if canDecide}
						<div class="space-y-5">
							<!-- Decision radio cards -->
							<div class="grid grid-cols-3 gap-3">
								<label class="cursor-pointer">
									<input
										type="radio"
										name="decision"
										value="APPROVED"
										bind:group={decision}
										class="sr-only"
									/>
									<div
										class="flex flex-col items-center justify-center gap-2 rounded-2xl border p-5 text-center transition-all
										{decision === 'APPROVED'
											? 'border-emerald-500 bg-emerald-500/10 text-emerald-600 ring-1 ring-emerald-500/50'
											: 'border-border/60 text-muted-foreground hover:bg-muted/30'}"
									>
										<CheckCircle2 size={26} />
										<span class="text-xs leading-tight font-extrabold">{ui.approve}</span>
										<span class="text-[10px] opacity-70">{ui.approveHint}</span>
									</div>
								</label>
								<label class="cursor-pointer">
									<input
										type="radio"
										name="decision"
										value="REVISION_REQUESTED"
										bind:group={decision}
										class="sr-only"
									/>
									<div
										class="flex flex-col items-center justify-center gap-2 rounded-2xl border p-5 text-center transition-all
										{decision === 'REVISION_REQUESTED'
											? 'border-amber-500 bg-amber-500/10 text-amber-600 ring-1 ring-amber-500/50'
											: 'border-border/60 text-muted-foreground hover:bg-muted/30'}"
									>
										<AlertCircle size={26} />
										<span class="text-xs leading-tight font-extrabold">{ui.revise}</span>
										<span class="text-[10px] opacity-70">{ui.reviseHint}</span>
									</div>
								</label>
								<label class="cursor-pointer">
									<input
										type="radio"
										name="decision"
										value="REJECTED"
										bind:group={decision}
										class="sr-only"
									/>
									<div
										class="flex flex-col items-center justify-center gap-2 rounded-2xl border p-5 text-center transition-all
										{decision === 'REJECTED'
											? 'border-destructive bg-destructive/10 text-destructive ring-1 ring-destructive/50'
											: 'border-border/60 text-muted-foreground hover:bg-muted/30'}"
									>
										<XCircle size={26} />
										<span class="text-xs leading-tight font-extrabold">{ui.reject}</span>
										<span class="text-[10px] opacity-70">{ui.rejectHint}</span>
									</div>
								</label>
							</div>

							<!-- Remarks -->
							<div class="space-y-2">
								<div class="flex items-center justify-between gap-3">
									<label
										for="ld-feedback"
										class="text-[11px] font-black tracking-widest text-muted-foreground uppercase"
									>
										{decision === 'REJECTED' || decision === 'REVISION_REQUESTED'
											? ui.directiveRequired
											: ui.directiveOptional}
									</label>
									<button
										onclick={generateAILeaderBrief}
										disabled={generatingLeaderBrief}
										class="flex shrink-0 items-center gap-2 rounded-lg bg-primary/10 px-3 py-1.5 text-xs font-bold text-primary transition-colors hover:bg-primary/20 disabled:opacity-50"
									>
										{#if generatingLeaderBrief}
											<Loader2 size={14} class="animate-spin" /> {ui.drafting}
										{:else}
											<Brain size={14} /> {ui.aiDraft}
										{/if}
									</button>
								</div>
								<textarea
									id="ld-feedback"
									bind:value={feedbackText}
									rows={4}
									placeholder={decision === 'APPROVED'
										? ui.approvePlaceholder
										: ui.aiDraftPlaceholder}
									class="w-full resize-y rounded-2xl border border-border/50 bg-muted/10 px-4 py-3 font-mono text-sm
										shadow-sm transition-all focus:bg-background focus:ring-2 focus:ring-primary/20 focus:outline-none"
								></textarea>
							</div>

							<!-- Submit -->
							<button
								onclick={submitApproval}
								disabled={submitting ||
									((decision === 'REJECTED' || decision === 'REVISION_REQUESTED') &&
										!feedbackText.trim())}
								class="flex h-14 w-full items-center justify-center gap-2 rounded-2xl text-sm font-extrabold shadow-lg shadow-black/5 transition-all
									{decision === 'APPROVED'
									? 'bg-emerald-500 text-white hover:bg-emerald-600'
									: decision === 'REJECTED'
										? 'bg-destructive text-white hover:bg-red-700'
										: 'bg-amber-500 text-black hover:bg-amber-600'}
									active:scale-[0.98] disabled:cursor-not-allowed disabled:opacity-40"
							>
								{#if submitting}
									<Loader2 size={18} class="animate-spin" /> {ui.processing}
								{:else if decision === 'APPROVED'}
									<CheckCircle2 size={18} /> {ui.approveNotify}
								{:else if decision === 'REJECTED'}
									<XCircle size={18} /> {ui.rejectNotify}
								{:else}
									<AlertCircle size={18} /> {ui.revisionNotify}
								{/if}
							</button>

							{#if decision === 'APPROVED'}
								<p
									class="flex items-center justify-center gap-1.5 text-center text-[11px] text-muted-foreground"
								>
									<Mail size={11} class="text-primary" />
									{ui.approveMailHint}
								</p>
							{:else if decision === 'REJECTED'}
								<p
									class="flex items-center justify-center gap-1.5 text-center text-[11px] text-muted-foreground"
								>
									<Mail size={11} class="text-destructive" />
									{ui.rejectMailHint}
								</p>
							{:else}
								<p
									class="flex items-center justify-center gap-1.5 text-center text-[11px] text-muted-foreground"
								>
									{ui.revisionHint}
								</p>
							{/if}
						</div>
					{:else if submitted || doc.status === 'APPROVED' || doc.status === 'REJECTED' || doc.status === 'REVISION_REQUESTED'}
						<!-- Post-decision state -->
						{@const isApproved = doc.status === 'APPROVED'}
						{@const isRejected = doc.status === 'REJECTED'}
						<div
							class="flex items-center gap-4 rounded-2xl border p-6
							{isApproved
								? 'border-emerald-500/20 bg-emerald-500/10 text-emerald-600'
								: isRejected
									? 'border-destructive/20 bg-destructive/10 text-destructive'
									: 'border-amber-500/20 bg-amber-500/10 text-amber-600'}"
						>
							{#if isApproved}
								<CheckCircle2 size={28} />
								<div>
									<p class="font-extrabold">{ui.approvedResult}</p>
									<p class="mt-0.5 flex items-center gap-1 text-xs font-medium opacity-80">
										<Mail size={11} />
										{ui.approvedMailSent}
									</p>
									<a
										href="/portal"
										class="mt-2 block text-xs font-semibold underline underline-offset-4 opacity-70 hover:opacity-100"
										>{ui.backMissionControl}</a
									>
								</div>
							{:else if isRejected}
								<XCircle size={28} />
								<div>
									<p class="font-extrabold">{ui.rejectedResult}</p>
									<p class="mt-0.5 flex items-center gap-1 text-xs font-medium opacity-80">
										<Mail size={11} />
										{ui.rejectedMailSent}
									</p>
									<a
										href="/portal"
										class="mt-2 block text-xs font-semibold underline underline-offset-4 opacity-70 hover:opacity-100"
										>{ui.backMissionControl}</a
									>
								</div>
							{:else}
								<AlertCircle size={28} />
								<div>
									<p class="font-extrabold">{ui.revisionResult}</p>
									<p class="mt-0.5 text-xs font-medium opacity-80">
										{ui.revisionStatusHint}
									</p>
									<a
										href="/portal"
										class="mt-2 block text-xs font-semibold underline underline-offset-4 opacity-70 hover:opacity-100"
										>{ui.backMissionControl}</a
									>
								</div>
							{/if}
						</div>
					{:else}
						<!-- Not in PENDING_APPROVAL state -->
						<div
							class="flex items-center gap-3 rounded-2xl border border-border/50 bg-muted/10 p-5 font-bold text-muted-foreground"
						>
							<CheckCircle2 size={24} />
							<div>
								{ui.notReady}
								<a
									href="/portal"
									class="mt-1 block text-xs font-semibold underline decoration-border underline-offset-4"
									>{ui.backMissionControl}</a
								>
							</div>
						</div>
					{/if}
				</div>
			</div>
		{:else if isLoading}
			<div class="flex flex-1 items-center justify-center">
				<Loader2 size={32} class="animate-spin text-primary" />
			</div>
		{:else if errorMsg}
			<div class="flex flex-1 items-center justify-center p-8">
				<p class="font-bold text-destructive">{errorMsg}</p>
			</div>
		{/if}
	</div>
</div>
