replicaCount: 2

image:
  repository: dvc/document-parser-service
  tag: latest

service:
  port: 8001

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 2Gi
