apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
  namespace: {{ .Values.global.namespace | default "dvc-system" }}
spec:
  selector:
    app: ingestion-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: ClusterIP
